### ISSUE TITLE
recipe for cluster which does not use virtualbox, uses an alternative, possibly lighter-weight provider

### ISSUE THREAD

**Issue by ssenator** [hpc/hpc-collab#18]
The ideal provider would be able to be run within an existing HPC job allocation, on an existing, unmodified HPC cluster.

Use case: on-going in-pipeline validation of upcoming, scheduled HPC changes

**Comment by katyfelkner** [comment]
a lighter-weight node would be cool for running a lot of nodes on Neutron, but this is lower priority for me than node recipes.

**Comment by ssenator** [comment]
kvm/libvirt is desirable, based on user input

**Comment by ssenator** [comment]
libvirt is functional, and provides the desirable feature of less context switching, less I/O and possibly others, at the expense of some existent libvirt bugs (#158 "Waiting for domain to be assigned IP address")

**Comment by ssenator** [comment]
future functionality will address aspects of this:
1) use of whole-node or multi-node snapshots and/or vagrant box creation and
2) porous membranes (containers) rather than virtual-machine implementations
