### ISSUE TITLE
create alias to just unprovision all compute nodes in a cluster

### ISSUE THREAD

**Issue by ssenator** [hpc/hpc-collab#91]

**Comment by katyfelkner** [comment]
this would also be quite helpful to me on the ML project - we are looking at mostly killing compute nodes and keeping the system services up.

**Comment by ssenator** [comment]
There's an alias to unprovision or poweroff individual nodes:  <nodename>- will poweroff the node (1 trailing minus sign)
<nodename>-- will unprovision the node. (2 trailing minus signs)
<nodename> will provision (bring up) the node. (just the nodename)
<nodename>! will force the node to unprovision and then reprovision.
I am interpreting the remaining task to create an alias to do analogous actions on *all* of the compute nodes in bulk.
